//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingTool.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class accessLog
    {
        public int Id { get; set; }
        public int Action_Id { get; set; }
        public int Role_Id { get; set; }
        public int User_Id { get; set; }
        public string Description { get; set; }
        public System.DateTime Time { get; set; }
        public int AccessPoint_Id { get; set; }
    
        public virtual accessPoint accessPoint { get; set; }
        public virtual role role { get; set; }
        public virtual user user { get; set; }
    }
}
